// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/Wei-Shaw/sub2api/ent"
	"github.com/Wei-Shaw/sub2api/internal/config"
	"github.com/Wei-Shaw/sub2api/internal/handler"
	"github.com/Wei-Shaw/sub2api/internal/handler/admin"
	"github.com/Wei-Shaw/sub2api/internal/payment"
	"github.com/Wei-Shaw/sub2api/internal/repository"
	"github.com/Wei-Shaw/sub2api/internal/server"
	"github.com/Wei-Shaw/sub2api/internal/server/middleware"
	"github.com/Wei-Shaw/sub2api/internal/service"
	"github.com/redis/go-redis/v9"
	"log/slog"
	"net/http"
	"sync"
	"time"
)

import (
	_ "embed"
	_ "github.com/Wei-Shaw/sub2api/ent/runtime"
)

// Injectors from wire.go:

func initializeApplication(buildInfo handler.BuildInfo) (*Application, error) {
	configConfig, err := config.ProvideConfig()
	if err != nil {
		return nil, err
	}
	client, err := repository.ProvideEnt(configConfig)
	if err != nil {
		return nil, err
	}
	db, err := repository.ProvideSQLDB(client)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(client, db)
	redeemCodeRepository := repository.NewRedeemCodeRepository(client)
	redisClient := repository.ProvideRedis(configConfig)
	refreshTokenCache := repository.NewRefreshTokenCache(redisClient)
	settingRepository := repository.NewSettingRepository(client)
	groupRepository := repository.NewGroupRepository(client, db)
	proxyRepository := repository.NewProxyRepository(client, db)
	settingService := service.ProvideSettingService(settingRepository, groupRepository, proxyRepository, configConfig)
	emailCache := repository.NewEmailCache(redisClient)
	emailService := service.NewEmailService(settingRepository, emailCache)
	turnstileVerifier := repository.NewTurnstileVerifier()
	turnstileService := service.NewTurnstileService(settingService, turnstileVerifier)
	emailQueueService := service.ProvideEmailQueueService(emailService)
	promoCodeRepository := repository.NewPromoCodeRepository(client)
	billingCache := repository.NewBillingCache(redisClient)
	userSubscriptionRepository := repository.NewUserSubscriptionRepository(client)
	apiKeyRepository := repository.NewAPIKeyRepository(client, db)
	userRPMCache := repository.NewUserRPMCache(redisClient)
	userGroupRateRepository := repository.NewUserGroupRateRepository(db)
	billingCacheService := service.ProvideBillingCacheService(billingCache, userRepository, userSubscriptionRepository, apiKeyRepository, userRPMCache, userGroupRateRepository, configConfig)
	apiKeyCache := repository.NewAPIKeyCache(redisClient)
	apiKeyService := service.ProvideAPIKeyService(apiKeyRepository, userRepository, groupRepository, userSubscriptionRepository, userGroupRateRepository, apiKeyCache, configConfig, billingCacheService)
	apiKeyAuthCacheInvalidator := service.ProvideAPIKeyAuthCacheInvalidator(apiKeyService)
	promoService := service.NewPromoService(promoCodeRepository, userRepository, billingCacheService, client, apiKeyAuthCacheInvalidator)
	subscriptionService := service.NewSubscriptionService(groupRepository, userSubscriptionRepository, billingCacheService, client, configConfig)
	affiliateRepository := repository.NewAffiliateRepository(client, db)
	affiliateService := service.NewAffiliateService(affiliateRepository, settingService, apiKeyAuthCacheInvalidator, billingCacheService)
	affiliateDistributionSettlementStore := affiliateRepository.(service.AffiliateDistributionUsageSettlementStore)
	affiliateDistributionSettlementProcessor := affiliateRepository.(service.AffiliateDistributionUsageSettlementProcessor)
	affiliateDistributionSettlementService := service.NewAffiliateDistributionSettlementService(affiliateDistributionSettlementStore, affiliateDistributionSettlementProcessor)
	affiliateDistributionMonthlyResetService := service.NewAffiliateDistributionMonthlyResetService(affiliateService)
	authService := service.NewAuthService(client, userRepository, redeemCodeRepository, refreshTokenCache, configConfig, settingService, emailService, turnstileService, emailQueueService, promoService, subscriptionService, affiliateService)
	userService := service.NewUserService(userRepository, settingRepository, apiKeyAuthCacheInvalidator, billingCache)
	redeemCache := repository.NewRedeemCache(redisClient)
	redeemService := service.NewRedeemService(redeemCodeRepository, userRepository, subscriptionService, redeemCache, billingCacheService, client, apiKeyAuthCacheInvalidator, affiliateService)
	secretEncryptor, err := repository.NewAESEncryptor(configConfig)
	if err != nil {
		return nil, err
	}
	totpCache := repository.NewTotpCache(redisClient)
	totpService := service.NewTotpService(userRepository, secretEncryptor, totpCache, settingService, emailService, emailQueueService)
	authHandler := handler.NewAuthHandler(configConfig, authService, userService, settingService, promoService, redeemService, totpService)
	userHandler := handler.NewUserHandler(userService, authService, emailService, emailCache, affiliateService)
	apiKeyHandler := handler.NewAPIKeyHandler(apiKeyService)
	usageLogRepository := repository.NewUsageLogRepository(client, db)
	usageService := service.NewUsageService(usageLogRepository, userRepository, client, apiKeyAuthCacheInvalidator)
	usageHandler := handler.NewUsageHandler(usageService, apiKeyService)
	redeemHandler := handler.NewRedeemHandler(redeemService)
	subscriptionHandler := handler.NewSubscriptionHandler(subscriptionService)
	announcementRepository := repository.NewAnnouncementRepository(client)
	announcementReadRepository := repository.NewAnnouncementReadRepository(client)
	announcementService := service.NewAnnouncementService(announcementRepository, announcementReadRepository, userRepository, userSubscriptionRepository)
	announcementHandler := handler.NewAnnouncementHandler(announcementService)
	channelMonitorRepository := repository.NewChannelMonitorRepository(client, db)
	channelMonitorService := service.ProvideChannelMonitorService(channelMonitorRepository, secretEncryptor)
	channelMonitorUserHandler := handler.NewChannelMonitorUserHandler(channelMonitorService, settingService)
	dashboardAggregationRepository := repository.NewDashboardAggregationRepository(db)
	dashboardStatsCache := repository.NewDashboardCache(redisClient, configConfig)
	dashboardService := service.NewDashboardService(usageLogRepository, dashboardAggregationRepository, dashboardStatsCache, configConfig)
	timingWheelService, err := service.ProvideTimingWheelService()
	if err != nil {
		return nil, err
	}
	dashboardAggregationService := service.ProvideDashboardAggregationService(dashboardAggregationRepository, timingWheelService, configConfig)
	dashboardHandler := admin.NewDashboardHandler(dashboardService, dashboardAggregationService)
	schedulerCache := repository.ProvideSchedulerCache(redisClient, configConfig)
	accountRepository := repository.NewAccountRepository(client, db, schedulerCache)
	proxyExitInfoProber := repository.NewProxyExitInfoProber(configConfig)
	proxyLatencyCache := repository.NewProxyLatencyCache(redisClient)
	privacyClientFactory := providePrivacyClientFactory()
	adminService := service.NewAdminService(userRepository, groupRepository, accountRepository, proxyRepository, apiKeyRepository, redeemCodeRepository, userGroupRateRepository, userRPMCache, billingCacheService, proxyExitInfoProber, proxyLatencyCache, apiKeyAuthCacheInvalidator, client, settingService, subscriptionService, userSubscriptionRepository, privacyClientFactory, usageLogRepository)
	concurrencyCache := repository.ProvideConcurrencyCache(redisClient, configConfig)
	concurrencyService := service.ProvideConcurrencyService(concurrencyCache, accountRepository, configConfig)
	adminUserHandler := admin.NewUserHandler(adminService, concurrencyService)
	sessionLimitCache := repository.ProvideSessionLimitCache(redisClient, configConfig)
	rpmCache := repository.NewRPMCache(redisClient)
	groupCapacityService := service.NewGroupCapacityService(accountRepository, groupRepository, concurrencyService, sessionLimitCache, rpmCache)
	groupHandler := admin.NewGroupHandler(adminService, dashboardService, groupCapacityService)
	claudeOAuthClient := repository.NewClaudeOAuthClient()
	oAuthService := service.NewOAuthService(proxyRepository, claudeOAuthClient)
	openAIOAuthClient := repository.NewOpenAIOAuthClient()
	openAIOAuthService := service.NewOpenAIOAuthService(proxyRepository, openAIOAuthClient)
	geminiOAuthClient := repository.NewGeminiOAuthClient(configConfig)
	geminiCliCodeAssistClient := repository.NewGeminiCliCodeAssistClient()
	driveClient := repository.NewGeminiDriveClient()
	geminiOAuthService := service.NewGeminiOAuthService(proxyRepository, geminiOAuthClient, geminiCliCodeAssistClient, driveClient, configConfig)
	antigravityOAuthService := service.NewAntigravityOAuthService(proxyRepository)
	geminiQuotaService := service.NewGeminiQuotaService(configConfig, settingRepository)
	tempUnschedCache := repository.NewTempUnschedCache(redisClient)
	timeoutCounterCache := repository.NewTimeoutCounterCache(redisClient)
	openAI403CounterCache := repository.NewOpenAI403CounterCache(redisClient)
	geminiTokenCache := repository.NewGeminiTokenCache(redisClient)
	compositeTokenCacheInvalidator := service.NewCompositeTokenCacheInvalidator(geminiTokenCache)
	rateLimitService := service.ProvideRateLimitService(accountRepository, usageLogRepository, configConfig, geminiQuotaService, tempUnschedCache, timeoutCounterCache, openAI403CounterCache, settingService, compositeTokenCacheInvalidator)
	httpUpstream := repository.NewHTTPUpstream(configConfig)
	claudeUsageFetcher := repository.NewClaudeUsageFetcher(httpUpstream)
	antigravityQuotaFetcher := service.NewAntigravityQuotaFetcher(proxyRepository)
	usageCache := service.NewUsageCache()
	identityCache := repository.NewIdentityCache(redisClient)
	tlsFingerprintProfileRepository := repository.NewTLSFingerprintProfileRepository(client)
	tlsFingerprintProfileCache := repository.NewTLSFingerprintProfileCache(redisClient)
	tlsFingerprintProfileService := service.NewTLSFingerprintProfileService(tlsFingerprintProfileRepository, tlsFingerprintProfileCache)
	accountUsageService := service.NewAccountUsageService(accountRepository, usageLogRepository, claudeUsageFetcher, geminiQuotaService, antigravityQuotaFetcher, usageCache, identityCache, tlsFingerprintProfileService)
	oAuthRefreshAPI := service.ProvideOAuthRefreshAPI(accountRepository, geminiTokenCache)
	geminiTokenProvider := service.ProvideGeminiTokenProvider(accountRepository, geminiTokenCache, geminiOAuthService, oAuthRefreshAPI)
	claudeTokenProvider := service.ProvideClaudeTokenProvider(accountRepository, geminiTokenCache, oAuthService, oAuthRefreshAPI)
	gatewayCache := repository.NewGatewayCache(redisClient)
	schedulerOutboxRepository := repository.NewSchedulerOutboxRepository(db)
	schedulerSnapshotService := service.ProvideSchedulerSnapshotService(schedulerCache, schedulerOutboxRepository, accountRepository, groupRepository, configConfig)
	antigravityTokenProvider := service.ProvideAntigravityTokenProvider(accountRepository, geminiTokenCache, antigravityOAuthService, oAuthRefreshAPI, tempUnschedCache)
	internal500CounterCache := repository.NewInternal500CounterCache(redisClient)
	antigravityGatewayService := service.NewAntigravityGatewayService(accountRepository, gatewayCache, schedulerSnapshotService, antigravityTokenProvider, rateLimitService, httpUpstream, settingService, internal500CounterCache)
	accountTestService := service.NewAccountTestService(accountRepository, geminiTokenProvider, claudeTokenProvider, antigravityGatewayService, httpUpstream, configConfig, tlsFingerprintProfileService)
	crsSyncService := service.NewCRSSyncService(accountRepository, proxyRepository, oAuthService, openAIOAuthService, geminiOAuthService, configConfig)
	accountHandler := admin.NewAccountHandler(adminService, oAuthService, openAIOAuthService, geminiOAuthService, antigravityOAuthService, rateLimitService, accountUsageService, accountTestService, concurrencyService, crsSyncService, sessionLimitCache, rpmCache, compositeTokenCacheInvalidator)
	adminAnnouncementHandler := admin.NewAnnouncementHandler(announcementService)
	dataManagementService := service.NewDataManagementService()
	dataManagementHandler := admin.NewDataManagementHandler(dataManagementService)
	backupObjectStoreFactory := repository.NewS3BackupStoreFactory()
	dbDumper := repository.NewPgDumper(configConfig)
	backupService := service.ProvideBackupService(settingRepository, configConfig, secretEncryptor, backupObjectStoreFactory, dbDumper)
	backupHandler := admin.NewBackupHandler(backupService, userService)
	oAuthHandler := admin.NewOAuthHandler(oAuthService)
	openAIOAuthHandler := admin.NewOpenAIOAuthHandler(openAIOAuthService, adminService)
	geminiOAuthHandler := admin.NewGeminiOAuthHandler(geminiOAuthService)
	antigravityOAuthHandler := admin.NewAntigravityOAuthHandler(antigravityOAuthService)
	proxyHandler := admin.NewProxyHandler(adminService)
	adminRedeemHandler := admin.NewRedeemHandler(adminService, redeemService)
	promoHandler := admin.NewPromoHandler(promoService)
	opsRepository := repository.NewOpsRepository(db)
	usageBillingRepository := repository.NewUsageBillingRepository(client, db)
	pricingRemoteClient := repository.ProvidePricingRemoteClient(configConfig)
	pricingService, err := service.ProvidePricingService(configConfig, pricingRemoteClient)
	if err != nil {
		return nil, err
	}
	billingService := service.NewBillingService(configConfig, pricingService)
	identityService := service.NewIdentityService(identityCache)
	deferredService := service.ProvideDeferredService(accountRepository, timingWheelService)
	digestSessionStore := service.NewDigestSessionStore()
	channelRepository := repository.NewChannelRepository(db)
	channelService := service.NewChannelService(channelRepository, groupRepository, apiKeyAuthCacheInvalidator, pricingService)
	modelPricingResolver := service.NewModelPricingResolver(channelService, billingService)
	balanceNotifyService := service.ProvideBalanceNotifyService(emailService, settingRepository, accountRepository)
	gatewayService := service.NewGatewayService(accountRepository, groupRepository, usageLogRepository, usageBillingRepository, userRepository, userSubscriptionRepository, userGroupRateRepository, gatewayCache, configConfig, schedulerSnapshotService, concurrencyService, billingService, rateLimitService, billingCacheService, identityService, httpUpstream, deferredService, claudeTokenProvider, sessionLimitCache, rpmCache, digestSessionStore, settingService, tlsFingerprintProfileService, channelService, modelPricingResolver, balanceNotifyService)
	gatewayService.SetAffiliateDistributionUsageSettlementService(affiliateDistributionSettlementService)
	openAITokenProvider := service.ProvideOpenAITokenProvider(accountRepository, geminiTokenCache, openAIOAuthService, oAuthRefreshAPI)
	openAIGatewayService := service.NewOpenAIGatewayService(accountRepository, usageLogRepository, usageBillingRepository, userRepository, userSubscriptionRepository, userGroupRateRepository, gatewayCache, configConfig, schedulerSnapshotService, concurrencyService, billingService, rateLimitService, billingCacheService, httpUpstream, deferredService, openAITokenProvider, modelPricingResolver, channelService, balanceNotifyService, settingService)
	openAIGatewayService.SetAffiliateDistributionUsageSettlementService(affiliateDistributionSettlementService)
	geminiMessagesCompatService := service.NewGeminiMessagesCompatService(accountRepository, groupRepository, gatewayCache, schedulerSnapshotService, geminiTokenProvider, rateLimitService, httpUpstream, antigravityGatewayService, configConfig)
	opsSystemLogSink := service.ProvideOpsSystemLogSink(opsRepository)
	opsService := service.NewOpsService(opsRepository, settingRepository, configConfig, accountRepository, userRepository, concurrencyService, gatewayService, openAIGatewayService, geminiMessagesCompatService, antigravityGatewayService, opsSystemLogSink)
	encryptionKey, err := payment.ProvideEncryptionKey(configConfig)
	if err != nil {
		return nil, err
	}
	paymentConfigService := service.ProvidePaymentConfigService(client, settingRepository, encryptionKey)
	registry := payment.ProvideRegistry()
	defaultLoadBalancer := payment.ProvideDefaultLoadBalancer(client, encryptionKey)
	paymentService := service.NewPaymentService(client, registry, defaultLoadBalancer, redeemService, subscriptionService, paymentConfigService, userRepository, groupRepository, affiliateService)
	settingHandler := admin.NewSettingHandler(settingService, emailService, turnstileService, opsService, paymentConfigService, paymentService)
	opsHandler := admin.NewOpsHandler(opsService)
	updateCache := repository.NewUpdateCache(redisClient)
	gitHubReleaseClient := repository.ProvideGitHubReleaseClient(configConfig)
	serviceBuildInfo := provideServiceBuildInfo(buildInfo)
	updateService := service.ProvideUpdateService(updateCache, gitHubReleaseClient, serviceBuildInfo)
	idempotencyRepository := repository.NewIdempotencyRepository(client, db)
	systemOperationLockService := service.ProvideSystemOperationLockService(idempotencyRepository, configConfig)
	systemHandler := handler.ProvideSystemHandler(updateService, systemOperationLockService)
	adminSubscriptionHandler := admin.NewSubscriptionHandler(subscriptionService)
	usageCleanupRepository := repository.NewUsageCleanupRepository(client, db)
	usageCleanupService := service.ProvideUsageCleanupService(usageCleanupRepository, timingWheelService, dashboardAggregationService, configConfig)
	adminUsageHandler := admin.NewUsageHandler(usageService, apiKeyService, adminService, usageCleanupService)
	userAttributeDefinitionRepository := repository.NewUserAttributeDefinitionRepository(client)
	userAttributeValueRepository := repository.NewUserAttributeValueRepository(client)
	userAttributeService := service.NewUserAttributeService(userAttributeDefinitionRepository, userAttributeValueRepository)
	userAttributeHandler := admin.NewUserAttributeHandler(userAttributeService)
	errorPassthroughRepository := repository.NewErrorPassthroughRepository(client)
	errorPassthroughCache := repository.NewErrorPassthroughCache(redisClient)
	errorPassthroughService := service.NewErrorPassthroughService(errorPassthroughRepository, errorPassthroughCache)
	errorPassthroughHandler := admin.NewErrorPassthroughHandler(errorPassthroughService)
	tlsFingerprintProfileHandler := admin.NewTLSFingerprintProfileHandler(tlsFingerprintProfileService)
	adminAPIKeyHandler := admin.NewAdminAPIKeyHandler(adminService)
	scheduledTestPlanRepository := repository.NewScheduledTestPlanRepository(db)
	scheduledTestResultRepository := repository.NewScheduledTestResultRepository(db)
	scheduledTestService := service.ProvideScheduledTestService(scheduledTestPlanRepository, scheduledTestResultRepository)
	scheduledTestHandler := admin.NewScheduledTestHandler(scheduledTestService)
	channelHandler := admin.NewChannelHandler(channelService, billingService)
	channelMonitorHandler := admin.NewChannelMonitorHandler(channelMonitorService)
	channelMonitorRequestTemplateRepository := repository.NewChannelMonitorRequestTemplateRepository(client, db)
	channelMonitorRequestTemplateService := service.NewChannelMonitorRequestTemplateService(channelMonitorRequestTemplateRepository)
	channelMonitorRequestTemplateHandler := admin.NewChannelMonitorRequestTemplateHandler(channelMonitorRequestTemplateService)
	contentModerationRepository := repository.NewContentModerationRepository(db)
	contentModerationHashCache := repository.NewContentModerationHashCache(redisClient)
	contentModerationService := service.NewContentModerationService(settingRepository, contentModerationRepository, contentModerationHashCache, groupRepository, userRepository, apiKeyAuthCacheInvalidator, emailService)
	contentModerationHandler := admin.NewContentModerationHandler(contentModerationService)
	paymentHandler := admin.NewPaymentHandler(paymentService, paymentConfigService)
	affiliateHandler := admin.NewAffiliateHandler(affiliateService, adminService, userService)
	adminHandlers := handler.ProvideAdminHandlers(dashboardHandler, adminUserHandler, groupHandler, accountHandler, adminAnnouncementHandler, dataManagementHandler, backupHandler, oAuthHandler, openAIOAuthHandler, geminiOAuthHandler, antigravityOAuthHandler, proxyHandler, adminRedeemHandler, promoHandler, settingHandler, opsHandler, systemHandler, adminSubscriptionHandler, adminUsageHandler, userAttributeHandler, errorPassthroughHandler, tlsFingerprintProfileHandler, adminAPIKeyHandler, scheduledTestHandler, channelHandler, channelMonitorHandler, channelMonitorRequestTemplateHandler, contentModerationHandler, paymentHandler, affiliateHandler)
	usageRecordWorkerPool := service.NewUsageRecordWorkerPool(configConfig)
	userMsgQueueCache := repository.NewUserMsgQueueCache(redisClient)
	userMessageQueueService := service.ProvideUserMessageQueueService(userMsgQueueCache, rpmCache, configConfig)
	gatewayHandler := handler.NewGatewayHandler(gatewayService, geminiMessagesCompatService, antigravityGatewayService, userService, concurrencyService, billingCacheService, usageService, apiKeyService, usageRecordWorkerPool, errorPassthroughService, contentModerationService, userMessageQueueService, configConfig, settingService)
	openAIGatewayHandler := handler.NewOpenAIGatewayHandler(openAIGatewayService, concurrencyService, billingCacheService, apiKeyService, usageRecordWorkerPool, errorPassthroughService, contentModerationService, configConfig)
	handlerSettingHandler := handler.ProvideSettingHandler(settingService, buildInfo)
	totpHandler := handler.NewTotpHandler(totpService)
	handlerPaymentHandler := handler.NewPaymentHandler(paymentService, paymentConfigService, channelService)
	paymentWebhookHandler := handler.NewPaymentWebhookHandler(paymentService, registry)
	availableChannelHandler := handler.NewAvailableChannelHandler(channelService, apiKeyService, settingService)
	idempotencyCoordinator := service.ProvideIdempotencyCoordinator(idempotencyRepository, configConfig)
	idempotencyCleanupService := service.ProvideIdempotencyCleanupService(idempotencyRepository, configConfig)
	handlers := handler.ProvideHandlers(authHandler, userHandler, apiKeyHandler, usageHandler, redeemHandler, subscriptionHandler, announcementHandler, channelMonitorUserHandler, adminHandlers, gatewayHandler, openAIGatewayHandler, handlerSettingHandler, totpHandler, handlerPaymentHandler, paymentWebhookHandler, availableChannelHandler, idempotencyCoordinator, idempotencyCleanupService)
	jwtAuthMiddleware := middleware.NewJWTAuthMiddleware(authService, userService)
	adminAuthMiddleware := middleware.NewAdminAuthMiddleware(authService, userService, settingService)
	apiKeyAuthMiddleware := middleware.NewAPIKeyAuthMiddleware(apiKeyService, subscriptionService, configConfig)
	engine := server.ProvideRouter(configConfig, handlers, jwtAuthMiddleware, adminAuthMiddleware, apiKeyAuthMiddleware, apiKeyService, subscriptionService, opsService, settingService, redisClient)
	httpServer := server.ProvideHTTPServer(configConfig, engine)
	opsMetricsCollector := service.ProvideOpsMetricsCollector(opsRepository, settingRepository, accountRepository, concurrencyService, db, redisClient, configConfig)
	opsAggregationService := service.ProvideOpsAggregationService(opsRepository, settingRepository, db, redisClient, configConfig)
	opsAlertEvaluatorService := service.ProvideOpsAlertEvaluatorService(opsService, opsRepository, emailService, redisClient, configConfig)
	opsCleanupService := service.ProvideOpsCleanupService(opsRepository, db, redisClient, configConfig, channelMonitorService, settingRepository, opsService)
	opsScheduledReportService := service.ProvideOpsScheduledReportService(opsService, userService, emailService, redisClient, configConfig)
	tokenRefreshService := service.ProvideTokenRefreshService(accountRepository, oAuthService, openAIOAuthService, geminiOAuthService, antigravityOAuthService, compositeTokenCacheInvalidator, schedulerCache, configConfig, tempUnschedCache, privacyClientFactory, proxyRepository, oAuthRefreshAPI)
	accountExpiryService := service.ProvideAccountExpiryService(accountRepository)
	subscriptionExpiryService := service.ProvideSubscriptionExpiryService(userSubscriptionRepository)
	scheduledTestRunnerService := service.ProvideScheduledTestRunnerService(scheduledTestPlanRepository, scheduledTestService, accountTestService, rateLimitService, configConfig)
	paymentOrderExpiryService := service.ProvidePaymentOrderExpiryService(paymentService)
	channelMonitorRunner := service.ProvideChannelMonitorRunner(channelMonitorService, settingService)
	cleanupInfra := cleanupInfrastructure{
		EntClient: client,
		Redis:     redisClient,
	}
	cleanupSvcSet := cleanupServices{
		OpsMetricsCollector:               opsMetricsCollector,
		OpsAggregationService:             opsAggregationService,
		OpsAlertEvaluatorService:          opsAlertEvaluatorService,
		OpsCleanupService:                 opsCleanupService,
		OpsScheduledReportService:         opsScheduledReportService,
		OpsSystemLogSink:                  opsSystemLogSink,
		SchedulerSnapshotService:          schedulerSnapshotService,
		TokenRefreshService:               tokenRefreshService,
		AccountExpiryService:              accountExpiryService,
		SubscriptionExpiryService:         subscriptionExpiryService,
		UsageCleanupService:               usageCleanupService,
		IdempotencyCleanupService:         idempotencyCleanupService,
		PricingService:                    pricingService,
		EmailQueueService:                 emailQueueService,
		BillingCacheService:               billingCacheService,
		UsageRecordWorkerPool:             usageRecordWorkerPool,
		SubscriptionService:               subscriptionService,
		OAuthService:                      oAuthService,
		OpenAIOAuthService:                openAIOAuthService,
		GeminiOAuthService:                geminiOAuthService,
		AntigravityOAuthService:           antigravityOAuthService,
		OpenAIGatewayService:              openAIGatewayService,
		ScheduledTestRunnerService:        scheduledTestRunnerService,
		BackupService:                     backupService,
		PaymentOrderExpiryService:         paymentOrderExpiryService,
		ChannelMonitorRunner:              channelMonitorRunner,
		AffiliateDistributionMonthlyReset: affiliateDistributionMonthlyResetService,
	}
	v := provideCleanup(cleanupInfra, cleanupSvcSet)
	application := &Application{
		Server:  httpServer,
		Cleanup: v,
	}
	return application, nil
}

// wire.go:

type Application struct {
	Server  *http.Server
	Cleanup func()
}

type cleanupStep struct {
	name string
	fn   func() error
}

type CleanupRegistry struct {
	parallel   []cleanupStep
	sequential []cleanupStep
}

func (r *CleanupRegistry) AddParallel(name string, fn func() error) {
	if fn == nil {
		return
	}
	r.parallel = append(r.parallel, cleanupStep{name: name, fn: fn})
}

func (r *CleanupRegistry) AddSequential(name string, fn func() error) {
	if fn == nil {
		return
	}
	r.sequential = append(r.sequential, cleanupStep{name: name, fn: fn})
}

func (r *CleanupRegistry) Run(ctx context.Context) {
	runParallel := func(steps []cleanupStep) {
		var wg sync.WaitGroup
		for i := range steps {
			step := steps[i]
			wg.Add(1)
			go func() {
				defer wg.Done()
				if err := step.fn(); err != nil {
					slog.Warn("cleanup step failed", "step", step.name, "error", err)
					return
				}
				slog.Info("cleanup step succeeded", "step", step.name)
			}()
		}
		wg.Wait()
	}

	runSequential := func(steps []cleanupStep) {
		for i := range steps {
			step := steps[i]
			if err := step.fn(); err != nil {
				slog.Warn("cleanup step failed", "step", step.name, "error", err)
				continue
			}
			slog.Info("cleanup step succeeded", "step", step.name)
		}
	}

	runParallel(r.parallel)
	runSequential(r.sequential)

	select {
	case <-ctx.Done():
		slog.Warn("cleanup timed out", "error", ctx.Err())
	default:
		slog.Info("cleanup steps completed")
	}
}

type cleanupInfrastructure struct {
	EntClient *ent.Client
	Redis     *redis.Client
}

func (c cleanupInfrastructure) Register(registry *CleanupRegistry) {
	registry.AddSequential("Redis", func() error {
		if c.Redis == nil {
			return nil
		}
		return c.Redis.Close()
	})
	registry.AddSequential("Ent", func() error {
		if c.EntClient == nil {
			return nil
		}
		return c.EntClient.Close()
	})
}

type cleanupServices struct {
	OpsMetricsCollector               *service.OpsMetricsCollector
	OpsAggregationService             *service.OpsAggregationService
	OpsAlertEvaluatorService          *service.OpsAlertEvaluatorService
	OpsCleanupService                 *service.OpsCleanupService
	OpsScheduledReportService         *service.OpsScheduledReportService
	OpsSystemLogSink                  *service.OpsSystemLogSink
	SchedulerSnapshotService          *service.SchedulerSnapshotService
	TokenRefreshService               *service.TokenRefreshService
	AccountExpiryService              *service.AccountExpiryService
	SubscriptionExpiryService         *service.SubscriptionExpiryService
	UsageCleanupService               *service.UsageCleanupService
	IdempotencyCleanupService         *service.IdempotencyCleanupService
	PricingService                    *service.PricingService
	EmailQueueService                 *service.EmailQueueService
	BillingCacheService               *service.BillingCacheService
	UsageRecordWorkerPool             *service.UsageRecordWorkerPool
	SubscriptionService               *service.SubscriptionService
	OAuthService                      *service.OAuthService
	OpenAIOAuthService                *service.OpenAIOAuthService
	GeminiOAuthService                *service.GeminiOAuthService
	AntigravityOAuthService           *service.AntigravityOAuthService
	OpenAIGatewayService              *service.OpenAIGatewayService
	ScheduledTestRunnerService        *service.ScheduledTestRunnerService
	BackupService                     *service.BackupService
	PaymentOrderExpiryService         *service.PaymentOrderExpiryService
	ChannelMonitorRunner              *service.ChannelMonitorRunner
	AffiliateDistributionMonthlyReset *service.AffiliateDistributionMonthlyResetService
}

func (s cleanupServices) Register(registry *CleanupRegistry) {
	registry.AddParallel("AffiliateDistributionMonthlyResetService", func() error {
		if s.AffiliateDistributionMonthlyReset != nil {
			s.AffiliateDistributionMonthlyReset.Stop()
		}
		return nil
	})
	registry.AddParallel("OpsScheduledReportService", func() error {
		if s.OpsScheduledReportService != nil {
			s.OpsScheduledReportService.Stop()
		}
		return nil
	})
	registry.AddParallel("OpsCleanupService", func() error {
		if s.OpsCleanupService != nil {
			s.OpsCleanupService.Stop()
		}
		return nil
	})
	registry.AddParallel("OpsSystemLogSink", func() error {
		if s.OpsSystemLogSink != nil {
			s.OpsSystemLogSink.Stop()
		}
		return nil
	})
	registry.AddParallel("OpsAlertEvaluatorService", func() error {
		if s.OpsAlertEvaluatorService != nil {
			s.OpsAlertEvaluatorService.Stop()
		}
		return nil
	})
	registry.AddParallel("OpsAggregationService", func() error {
		if s.OpsAggregationService != nil {
			s.OpsAggregationService.Stop()
		}
		return nil
	})
	registry.AddParallel("OpsMetricsCollector", func() error {
		if s.OpsMetricsCollector != nil {
			s.OpsMetricsCollector.Stop()
		}
		return nil
	})
	registry.AddParallel("SchedulerSnapshotService", func() error {
		if s.SchedulerSnapshotService != nil {
			s.SchedulerSnapshotService.Stop()
		}
		return nil
	})
	registry.AddParallel("UsageCleanupService", func() error {
		if s.UsageCleanupService != nil {
			s.UsageCleanupService.Stop()
		}
		return nil
	})
	registry.AddParallel("IdempotencyCleanupService", func() error {
		if s.IdempotencyCleanupService != nil {
			s.IdempotencyCleanupService.Stop()
		}
		return nil
	})
	registry.AddParallel("TokenRefreshService", func() error {
		if s.TokenRefreshService != nil {
			s.TokenRefreshService.Stop()
		}
		return nil
	})
	registry.AddParallel("AccountExpiryService", func() error {
		if s.AccountExpiryService != nil {
			s.AccountExpiryService.Stop()
		}
		return nil
	})
	registry.AddParallel("SubscriptionExpiryService", func() error {
		if s.SubscriptionExpiryService != nil {
			s.SubscriptionExpiryService.Stop()
		}
		return nil
	})
	registry.AddParallel("SubscriptionService", func() error {
		if s.SubscriptionService != nil {
			s.SubscriptionService.Stop()
		}
		return nil
	})
	registry.AddParallel("PricingService", func() error {
		if s.PricingService != nil {
			s.PricingService.Stop()
		}
		return nil
	})
	registry.AddParallel("EmailQueueService", func() error {
		if s.EmailQueueService != nil {
			s.EmailQueueService.Stop()
		}
		return nil
	})
	registry.AddParallel("BillingCacheService", func() error {
		if s.BillingCacheService != nil {
			s.BillingCacheService.Stop()
		}
		return nil
	})
	registry.AddParallel("UsageRecordWorkerPool", func() error {
		if s.UsageRecordWorkerPool != nil {
			s.UsageRecordWorkerPool.Stop()
		}
		return nil
	})
	registry.AddParallel("OAuthService", func() error {
		if s.OAuthService != nil {
			s.OAuthService.Stop()
		}
		return nil
	})
	registry.AddParallel("OpenAIOAuthService", func() error {
		if s.OpenAIOAuthService != nil {
			s.OpenAIOAuthService.Stop()
		}
		return nil
	})
	registry.AddParallel("GeminiOAuthService", func() error {
		if s.GeminiOAuthService != nil {
			s.GeminiOAuthService.Stop()
		}
		return nil
	})
	registry.AddParallel("AntigravityOAuthService", func() error {
		if s.AntigravityOAuthService != nil {
			s.AntigravityOAuthService.Stop()
		}
		return nil
	})
	registry.AddParallel("OpenAIWSPool", func() error {
		if s.OpenAIGatewayService != nil {
			s.OpenAIGatewayService.CloseOpenAIWSPool()
		}
		return nil
	})
	registry.AddParallel("ScheduledTestRunnerService", func() error {
		if s.ScheduledTestRunnerService != nil {
			s.ScheduledTestRunnerService.Stop()
		}
		return nil
	})
	registry.AddParallel("BackupService", func() error {
		if s.BackupService != nil {
			s.BackupService.Stop()
		}
		return nil
	})
	registry.AddParallel("PaymentOrderExpiryService", func() error {
		if s.PaymentOrderExpiryService != nil {
			s.PaymentOrderExpiryService.Stop()
		}
		return nil
	})
	registry.AddParallel("ChannelMonitorRunner", func() error {
		if s.ChannelMonitorRunner != nil {
			s.ChannelMonitorRunner.Stop()
		}
		return nil
	})
}

func providePrivacyClientFactory() service.PrivacyClientFactory {
	return repository.CreatePrivacyReqClient
}

func provideServiceBuildInfo(buildInfo handler.BuildInfo) service.BuildInfo {
	return service.BuildInfo{
		Version:   buildInfo.Version,
		BuildType: buildInfo.BuildType,
	}
}

func provideCleanup(infra cleanupInfrastructure, services cleanupServices) func() {
	return func() {
		ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()

		registry := &CleanupRegistry{}
		services.Register(registry)
		infra.Register(registry)
		registry.Run(ctx)
	}
}
